//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaPresentacion.ServiceReferenceDGAC {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ws/", ConfigurationName="ServiceReferenceDGAC.webservice_dgac")]
    public interface webservice_dgac {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/webservice_dgac/MultasByRutRequest", ReplyAction="http://ws/webservice_dgac/MultasByRutResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        CapaPresentacion.ServiceReferenceDGAC.MultasByRutResponse MultasByRut(CapaPresentacion.ServiceReferenceDGAC.MultasByRutRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/webservice_dgac/MultasByRutRequest", ReplyAction="http://ws/webservice_dgac/MultasByRutResponse")]
        System.Threading.Tasks.Task<CapaPresentacion.ServiceReferenceDGAC.MultasByRutResponse> MultasByRutAsync(CapaPresentacion.ServiceReferenceDGAC.MultasByRutRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/webservice_dgac/AeronavesByFechaRequest", ReplyAction="http://ws/webservice_dgac/AeronavesByFechaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        CapaPresentacion.ServiceReferenceDGAC.AeronavesByFechaResponse AeronavesByFecha(CapaPresentacion.ServiceReferenceDGAC.AeronavesByFechaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/webservice_dgac/AeronavesByFechaRequest", ReplyAction="http://ws/webservice_dgac/AeronavesByFechaResponse")]
        System.Threading.Tasks.Task<CapaPresentacion.ServiceReferenceDGAC.AeronavesByFechaResponse> AeronavesByFechaAsync(CapaPresentacion.ServiceReferenceDGAC.AeronavesByFechaRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/webservice_dgac/LicenciasByRutRequest", ReplyAction="http://ws/webservice_dgac/LicenciasByRutResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        CapaPresentacion.ServiceReferenceDGAC.LicenciasByRutResponse LicenciasByRut(CapaPresentacion.ServiceReferenceDGAC.LicenciasByRutRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/webservice_dgac/LicenciasByRutRequest", ReplyAction="http://ws/webservice_dgac/LicenciasByRutResponse")]
        System.Threading.Tasks.Task<CapaPresentacion.ServiceReferenceDGAC.LicenciasByRutResponse> LicenciasByRutAsync(CapaPresentacion.ServiceReferenceDGAC.LicenciasByRutRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/webservice_dgac/AeronavesListarRequest", ReplyAction="http://ws/webservice_dgac/AeronavesListarResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        CapaPresentacion.ServiceReferenceDGAC.AeronavesListarResponse AeronavesListar(CapaPresentacion.ServiceReferenceDGAC.AeronavesListarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/webservice_dgac/AeronavesListarRequest", ReplyAction="http://ws/webservice_dgac/AeronavesListarResponse")]
        System.Threading.Tasks.Task<CapaPresentacion.ServiceReferenceDGAC.AeronavesListarResponse> AeronavesListarAsync(CapaPresentacion.ServiceReferenceDGAC.AeronavesListarRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/webservice_dgac/existeLicenciaRequest", ReplyAction="http://ws/webservice_dgac/existeLicenciaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        CapaPresentacion.ServiceReferenceDGAC.existeLicenciaResponse existeLicencia(CapaPresentacion.ServiceReferenceDGAC.existeLicenciaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/webservice_dgac/existeLicenciaRequest", ReplyAction="http://ws/webservice_dgac/existeLicenciaResponse")]
        System.Threading.Tasks.Task<CapaPresentacion.ServiceReferenceDGAC.existeLicenciaResponse> existeLicenciaAsync(CapaPresentacion.ServiceReferenceDGAC.existeLicenciaRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/webservice_dgac/validarMultasbyRutRequest", ReplyAction="http://ws/webservice_dgac/validarMultasbyRutResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        CapaPresentacion.ServiceReferenceDGAC.validarMultasbyRutResponse validarMultasbyRut(CapaPresentacion.ServiceReferenceDGAC.validarMultasbyRutRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/webservice_dgac/validarMultasbyRutRequest", ReplyAction="http://ws/webservice_dgac/validarMultasbyRutResponse")]
        System.Threading.Tasks.Task<CapaPresentacion.ServiceReferenceDGAC.validarMultasbyRutResponse> validarMultasbyRutAsync(CapaPresentacion.ServiceReferenceDGAC.validarMultasbyRutRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/webservice_dgac/AeronaveByPatenteRequest", ReplyAction="http://ws/webservice_dgac/AeronaveByPatenteResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        CapaPresentacion.ServiceReferenceDGAC.AeronaveByPatenteResponse AeronaveByPatente(CapaPresentacion.ServiceReferenceDGAC.AeronaveByPatenteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/webservice_dgac/AeronaveByPatenteRequest", ReplyAction="http://ws/webservice_dgac/AeronaveByPatenteResponse")]
        System.Threading.Tasks.Task<CapaPresentacion.ServiceReferenceDGAC.AeronaveByPatenteResponse> AeronaveByPatenteAsync(CapaPresentacion.ServiceReferenceDGAC.AeronaveByPatenteRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/webservice_dgac/validarAeronaveByPatenteRequest", ReplyAction="http://ws/webservice_dgac/validarAeronaveByPatenteResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        CapaPresentacion.ServiceReferenceDGAC.validarAeronaveByPatenteResponse validarAeronaveByPatente(CapaPresentacion.ServiceReferenceDGAC.validarAeronaveByPatenteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/webservice_dgac/validarAeronaveByPatenteRequest", ReplyAction="http://ws/webservice_dgac/validarAeronaveByPatenteResponse")]
        System.Threading.Tasks.Task<CapaPresentacion.ServiceReferenceDGAC.validarAeronaveByPatenteResponse> validarAeronaveByPatenteAsync(CapaPresentacion.ServiceReferenceDGAC.validarAeronaveByPatenteRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/webservice_dgac/fechaAeronavegabilidad_por_patenteRequest", ReplyAction="http://ws/webservice_dgac/fechaAeronavegabilidad_por_patenteResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        CapaPresentacion.ServiceReferenceDGAC.fechaAeronavegabilidad_por_patenteResponse fechaAeronavegabilidad_por_patente(CapaPresentacion.ServiceReferenceDGAC.fechaAeronavegabilidad_por_patenteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/webservice_dgac/fechaAeronavegabilidad_por_patenteRequest", ReplyAction="http://ws/webservice_dgac/fechaAeronavegabilidad_por_patenteResponse")]
        System.Threading.Tasks.Task<CapaPresentacion.ServiceReferenceDGAC.fechaAeronavegabilidad_por_patenteResponse> fechaAeronavegabilidad_por_patenteAsync(CapaPresentacion.ServiceReferenceDGAC.fechaAeronavegabilidad_por_patenteRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws/")]
    public partial class clMulta : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string descField;
        
        private string es_invalidanteField;
        
        private int idField;
        
        private string rutField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string desc {
            get {
                return this.descField;
            }
            set {
                this.descField = value;
                this.RaisePropertyChanged("desc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string es_invalidante {
            get {
                return this.es_invalidanteField;
            }
            set {
                this.es_invalidanteField = value;
                this.RaisePropertyChanged("es_invalidante");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string rut {
            get {
                return this.rutField;
            }
            set {
                this.rutField = value;
                this.RaisePropertyChanged("rut");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws/")]
    public partial class clLicencia : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private int nro_licenciaField;
        
        private string rutField;
        
        private string tipo_aeronaveField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int nro_licencia {
            get {
                return this.nro_licenciaField;
            }
            set {
                this.nro_licenciaField = value;
                this.RaisePropertyChanged("nro_licencia");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string rut {
            get {
                return this.rutField;
            }
            set {
                this.rutField = value;
                this.RaisePropertyChanged("rut");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string tipo_aeronave {
            get {
                return this.tipo_aeronaveField;
            }
            set {
                this.tipo_aeronaveField = value;
                this.RaisePropertyChanged("tipo_aeronave");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws/")]
    public partial class clAeronave : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.DateTime fecha_aeronavegabilidadField;
        
        private bool fecha_aeronavegabilidadFieldSpecified;
        
        private string patenteField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public System.DateTime fecha_aeronavegabilidad {
            get {
                return this.fecha_aeronavegabilidadField;
            }
            set {
                this.fecha_aeronavegabilidadField = value;
                this.RaisePropertyChanged("fecha_aeronavegabilidad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fecha_aeronavegabilidadSpecified {
            get {
                return this.fecha_aeronavegabilidadFieldSpecified;
            }
            set {
                this.fecha_aeronavegabilidadFieldSpecified = value;
                this.RaisePropertyChanged("fecha_aeronavegabilidadSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string patente {
            get {
                return this.patenteField;
            }
            set {
                this.patenteField = value;
                this.RaisePropertyChanged("patente");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="MultasByRut", WrapperNamespace="http://ws/", IsWrapped=true)]
    public partial class MultasByRutRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string rut;
        
        public MultasByRutRequest() {
        }
        
        public MultasByRutRequest(string rut) {
            this.rut = rut;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="MultasByRutResponse", WrapperNamespace="http://ws/", IsWrapped=true)]
    public partial class MultasByRutResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CapaPresentacion.ServiceReferenceDGAC.clMulta[] @return;
        
        public MultasByRutResponse() {
        }
        
        public MultasByRutResponse(CapaPresentacion.ServiceReferenceDGAC.clMulta[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AeronavesByFecha", WrapperNamespace="http://ws/", IsWrapped=true)]
    public partial class AeronavesByFechaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string fecha;
        
        public AeronavesByFechaRequest() {
        }
        
        public AeronavesByFechaRequest(string fecha) {
            this.fecha = fecha;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AeronavesByFechaResponse", WrapperNamespace="http://ws/", IsWrapped=true)]
    public partial class AeronavesByFechaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CapaPresentacion.ServiceReferenceDGAC.clAeronave[] @return;
        
        public AeronavesByFechaResponse() {
        }
        
        public AeronavesByFechaResponse(CapaPresentacion.ServiceReferenceDGAC.clAeronave[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LicenciasByRut", WrapperNamespace="http://ws/", IsWrapped=true)]
    public partial class LicenciasByRutRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string rut;
        
        public LicenciasByRutRequest() {
        }
        
        public LicenciasByRutRequest(string rut) {
            this.rut = rut;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LicenciasByRutResponse", WrapperNamespace="http://ws/", IsWrapped=true)]
    public partial class LicenciasByRutResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CapaPresentacion.ServiceReferenceDGAC.clLicencia[] @return;
        
        public LicenciasByRutResponse() {
        }
        
        public LicenciasByRutResponse(CapaPresentacion.ServiceReferenceDGAC.clLicencia[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AeronavesListar", WrapperNamespace="http://ws/", IsWrapped=true)]
    public partial class AeronavesListarRequest {
        
        public AeronavesListarRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AeronavesListarResponse", WrapperNamespace="http://ws/", IsWrapped=true)]
    public partial class AeronavesListarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CapaPresentacion.ServiceReferenceDGAC.clAeronave[] @return;
        
        public AeronavesListarResponse() {
        }
        
        public AeronavesListarResponse(CapaPresentacion.ServiceReferenceDGAC.clAeronave[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="existeLicencia", WrapperNamespace="http://ws/", IsWrapped=true)]
    public partial class existeLicenciaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int nro_licencia;
        
        public existeLicenciaRequest() {
        }
        
        public existeLicenciaRequest(int nro_licencia) {
            this.nro_licencia = nro_licencia;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="existeLicenciaResponse", WrapperNamespace="http://ws/", IsWrapped=true)]
    public partial class existeLicenciaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public existeLicenciaResponse() {
        }
        
        public existeLicenciaResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="validarMultasbyRut", WrapperNamespace="http://ws/", IsWrapped=true)]
    public partial class validarMultasbyRutRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string rut;
        
        public validarMultasbyRutRequest() {
        }
        
        public validarMultasbyRutRequest(string rut) {
            this.rut = rut;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="validarMultasbyRutResponse", WrapperNamespace="http://ws/", IsWrapped=true)]
    public partial class validarMultasbyRutResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public validarMultasbyRutResponse() {
        }
        
        public validarMultasbyRutResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AeronaveByPatente", WrapperNamespace="http://ws/", IsWrapped=true)]
    public partial class AeronaveByPatenteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string patente;
        
        public AeronaveByPatenteRequest() {
        }
        
        public AeronaveByPatenteRequest(string patente) {
            this.patente = patente;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AeronaveByPatenteResponse", WrapperNamespace="http://ws/", IsWrapped=true)]
    public partial class AeronaveByPatenteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CapaPresentacion.ServiceReferenceDGAC.clAeronave[] @return;
        
        public AeronaveByPatenteResponse() {
        }
        
        public AeronaveByPatenteResponse(CapaPresentacion.ServiceReferenceDGAC.clAeronave[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="validarAeronaveByPatente", WrapperNamespace="http://ws/", IsWrapped=true)]
    public partial class validarAeronaveByPatenteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string patente;
        
        public validarAeronaveByPatenteRequest() {
        }
        
        public validarAeronaveByPatenteRequest(string patente) {
            this.patente = patente;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="validarAeronaveByPatenteResponse", WrapperNamespace="http://ws/", IsWrapped=true)]
    public partial class validarAeronaveByPatenteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public validarAeronaveByPatenteResponse() {
        }
        
        public validarAeronaveByPatenteResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="fechaAeronavegabilidad_por_patente", WrapperNamespace="http://ws/", IsWrapped=true)]
    public partial class fechaAeronavegabilidad_por_patenteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string patente;
        
        public fechaAeronavegabilidad_por_patenteRequest() {
        }
        
        public fechaAeronavegabilidad_por_patenteRequest(string patente) {
            this.patente = patente;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="fechaAeronavegabilidad_por_patenteResponse", WrapperNamespace="http://ws/", IsWrapped=true)]
    public partial class fechaAeronavegabilidad_por_patenteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public fechaAeronavegabilidad_por_patenteResponse() {
        }
        
        public fechaAeronavegabilidad_por_patenteResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface webservice_dgacChannel : CapaPresentacion.ServiceReferenceDGAC.webservice_dgac, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class webservice_dgacClient : System.ServiceModel.ClientBase<CapaPresentacion.ServiceReferenceDGAC.webservice_dgac>, CapaPresentacion.ServiceReferenceDGAC.webservice_dgac {
        
        public webservice_dgacClient() {
        }
        
        public webservice_dgacClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public webservice_dgacClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public webservice_dgacClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public webservice_dgacClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CapaPresentacion.ServiceReferenceDGAC.MultasByRutResponse CapaPresentacion.ServiceReferenceDGAC.webservice_dgac.MultasByRut(CapaPresentacion.ServiceReferenceDGAC.MultasByRutRequest request) {
            return base.Channel.MultasByRut(request);
        }
        
        public CapaPresentacion.ServiceReferenceDGAC.clMulta[] MultasByRut(string rut) {
            CapaPresentacion.ServiceReferenceDGAC.MultasByRutRequest inValue = new CapaPresentacion.ServiceReferenceDGAC.MultasByRutRequest();
            inValue.rut = rut;
            CapaPresentacion.ServiceReferenceDGAC.MultasByRutResponse retVal = ((CapaPresentacion.ServiceReferenceDGAC.webservice_dgac)(this)).MultasByRut(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CapaPresentacion.ServiceReferenceDGAC.MultasByRutResponse> CapaPresentacion.ServiceReferenceDGAC.webservice_dgac.MultasByRutAsync(CapaPresentacion.ServiceReferenceDGAC.MultasByRutRequest request) {
            return base.Channel.MultasByRutAsync(request);
        }
        
        public System.Threading.Tasks.Task<CapaPresentacion.ServiceReferenceDGAC.MultasByRutResponse> MultasByRutAsync(string rut) {
            CapaPresentacion.ServiceReferenceDGAC.MultasByRutRequest inValue = new CapaPresentacion.ServiceReferenceDGAC.MultasByRutRequest();
            inValue.rut = rut;
            return ((CapaPresentacion.ServiceReferenceDGAC.webservice_dgac)(this)).MultasByRutAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CapaPresentacion.ServiceReferenceDGAC.AeronavesByFechaResponse CapaPresentacion.ServiceReferenceDGAC.webservice_dgac.AeronavesByFecha(CapaPresentacion.ServiceReferenceDGAC.AeronavesByFechaRequest request) {
            return base.Channel.AeronavesByFecha(request);
        }
        
        public CapaPresentacion.ServiceReferenceDGAC.clAeronave[] AeronavesByFecha(string fecha) {
            CapaPresentacion.ServiceReferenceDGAC.AeronavesByFechaRequest inValue = new CapaPresentacion.ServiceReferenceDGAC.AeronavesByFechaRequest();
            inValue.fecha = fecha;
            CapaPresentacion.ServiceReferenceDGAC.AeronavesByFechaResponse retVal = ((CapaPresentacion.ServiceReferenceDGAC.webservice_dgac)(this)).AeronavesByFecha(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CapaPresentacion.ServiceReferenceDGAC.AeronavesByFechaResponse> CapaPresentacion.ServiceReferenceDGAC.webservice_dgac.AeronavesByFechaAsync(CapaPresentacion.ServiceReferenceDGAC.AeronavesByFechaRequest request) {
            return base.Channel.AeronavesByFechaAsync(request);
        }
        
        public System.Threading.Tasks.Task<CapaPresentacion.ServiceReferenceDGAC.AeronavesByFechaResponse> AeronavesByFechaAsync(string fecha) {
            CapaPresentacion.ServiceReferenceDGAC.AeronavesByFechaRequest inValue = new CapaPresentacion.ServiceReferenceDGAC.AeronavesByFechaRequest();
            inValue.fecha = fecha;
            return ((CapaPresentacion.ServiceReferenceDGAC.webservice_dgac)(this)).AeronavesByFechaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CapaPresentacion.ServiceReferenceDGAC.LicenciasByRutResponse CapaPresentacion.ServiceReferenceDGAC.webservice_dgac.LicenciasByRut(CapaPresentacion.ServiceReferenceDGAC.LicenciasByRutRequest request) {
            return base.Channel.LicenciasByRut(request);
        }
        
        public CapaPresentacion.ServiceReferenceDGAC.clLicencia[] LicenciasByRut(string rut) {
            CapaPresentacion.ServiceReferenceDGAC.LicenciasByRutRequest inValue = new CapaPresentacion.ServiceReferenceDGAC.LicenciasByRutRequest();
            inValue.rut = rut;
            CapaPresentacion.ServiceReferenceDGAC.LicenciasByRutResponse retVal = ((CapaPresentacion.ServiceReferenceDGAC.webservice_dgac)(this)).LicenciasByRut(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CapaPresentacion.ServiceReferenceDGAC.LicenciasByRutResponse> CapaPresentacion.ServiceReferenceDGAC.webservice_dgac.LicenciasByRutAsync(CapaPresentacion.ServiceReferenceDGAC.LicenciasByRutRequest request) {
            return base.Channel.LicenciasByRutAsync(request);
        }
        
        public System.Threading.Tasks.Task<CapaPresentacion.ServiceReferenceDGAC.LicenciasByRutResponse> LicenciasByRutAsync(string rut) {
            CapaPresentacion.ServiceReferenceDGAC.LicenciasByRutRequest inValue = new CapaPresentacion.ServiceReferenceDGAC.LicenciasByRutRequest();
            inValue.rut = rut;
            return ((CapaPresentacion.ServiceReferenceDGAC.webservice_dgac)(this)).LicenciasByRutAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CapaPresentacion.ServiceReferenceDGAC.AeronavesListarResponse CapaPresentacion.ServiceReferenceDGAC.webservice_dgac.AeronavesListar(CapaPresentacion.ServiceReferenceDGAC.AeronavesListarRequest request) {
            return base.Channel.AeronavesListar(request);
        }
        
        public CapaPresentacion.ServiceReferenceDGAC.clAeronave[] AeronavesListar() {
            CapaPresentacion.ServiceReferenceDGAC.AeronavesListarRequest inValue = new CapaPresentacion.ServiceReferenceDGAC.AeronavesListarRequest();
            CapaPresentacion.ServiceReferenceDGAC.AeronavesListarResponse retVal = ((CapaPresentacion.ServiceReferenceDGAC.webservice_dgac)(this)).AeronavesListar(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CapaPresentacion.ServiceReferenceDGAC.AeronavesListarResponse> CapaPresentacion.ServiceReferenceDGAC.webservice_dgac.AeronavesListarAsync(CapaPresentacion.ServiceReferenceDGAC.AeronavesListarRequest request) {
            return base.Channel.AeronavesListarAsync(request);
        }
        
        public System.Threading.Tasks.Task<CapaPresentacion.ServiceReferenceDGAC.AeronavesListarResponse> AeronavesListarAsync() {
            CapaPresentacion.ServiceReferenceDGAC.AeronavesListarRequest inValue = new CapaPresentacion.ServiceReferenceDGAC.AeronavesListarRequest();
            return ((CapaPresentacion.ServiceReferenceDGAC.webservice_dgac)(this)).AeronavesListarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CapaPresentacion.ServiceReferenceDGAC.existeLicenciaResponse CapaPresentacion.ServiceReferenceDGAC.webservice_dgac.existeLicencia(CapaPresentacion.ServiceReferenceDGAC.existeLicenciaRequest request) {
            return base.Channel.existeLicencia(request);
        }
        
        public bool existeLicencia(int nro_licencia) {
            CapaPresentacion.ServiceReferenceDGAC.existeLicenciaRequest inValue = new CapaPresentacion.ServiceReferenceDGAC.existeLicenciaRequest();
            inValue.nro_licencia = nro_licencia;
            CapaPresentacion.ServiceReferenceDGAC.existeLicenciaResponse retVal = ((CapaPresentacion.ServiceReferenceDGAC.webservice_dgac)(this)).existeLicencia(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CapaPresentacion.ServiceReferenceDGAC.existeLicenciaResponse> CapaPresentacion.ServiceReferenceDGAC.webservice_dgac.existeLicenciaAsync(CapaPresentacion.ServiceReferenceDGAC.existeLicenciaRequest request) {
            return base.Channel.existeLicenciaAsync(request);
        }
        
        public System.Threading.Tasks.Task<CapaPresentacion.ServiceReferenceDGAC.existeLicenciaResponse> existeLicenciaAsync(int nro_licencia) {
            CapaPresentacion.ServiceReferenceDGAC.existeLicenciaRequest inValue = new CapaPresentacion.ServiceReferenceDGAC.existeLicenciaRequest();
            inValue.nro_licencia = nro_licencia;
            return ((CapaPresentacion.ServiceReferenceDGAC.webservice_dgac)(this)).existeLicenciaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CapaPresentacion.ServiceReferenceDGAC.validarMultasbyRutResponse CapaPresentacion.ServiceReferenceDGAC.webservice_dgac.validarMultasbyRut(CapaPresentacion.ServiceReferenceDGAC.validarMultasbyRutRequest request) {
            return base.Channel.validarMultasbyRut(request);
        }
        
        public bool validarMultasbyRut(string rut) {
            CapaPresentacion.ServiceReferenceDGAC.validarMultasbyRutRequest inValue = new CapaPresentacion.ServiceReferenceDGAC.validarMultasbyRutRequest();
            inValue.rut = rut;
            CapaPresentacion.ServiceReferenceDGAC.validarMultasbyRutResponse retVal = ((CapaPresentacion.ServiceReferenceDGAC.webservice_dgac)(this)).validarMultasbyRut(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CapaPresentacion.ServiceReferenceDGAC.validarMultasbyRutResponse> CapaPresentacion.ServiceReferenceDGAC.webservice_dgac.validarMultasbyRutAsync(CapaPresentacion.ServiceReferenceDGAC.validarMultasbyRutRequest request) {
            return base.Channel.validarMultasbyRutAsync(request);
        }
        
        public System.Threading.Tasks.Task<CapaPresentacion.ServiceReferenceDGAC.validarMultasbyRutResponse> validarMultasbyRutAsync(string rut) {
            CapaPresentacion.ServiceReferenceDGAC.validarMultasbyRutRequest inValue = new CapaPresentacion.ServiceReferenceDGAC.validarMultasbyRutRequest();
            inValue.rut = rut;
            return ((CapaPresentacion.ServiceReferenceDGAC.webservice_dgac)(this)).validarMultasbyRutAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CapaPresentacion.ServiceReferenceDGAC.AeronaveByPatenteResponse CapaPresentacion.ServiceReferenceDGAC.webservice_dgac.AeronaveByPatente(CapaPresentacion.ServiceReferenceDGAC.AeronaveByPatenteRequest request) {
            return base.Channel.AeronaveByPatente(request);
        }
        
        public CapaPresentacion.ServiceReferenceDGAC.clAeronave[] AeronaveByPatente(string patente) {
            CapaPresentacion.ServiceReferenceDGAC.AeronaveByPatenteRequest inValue = new CapaPresentacion.ServiceReferenceDGAC.AeronaveByPatenteRequest();
            inValue.patente = patente;
            CapaPresentacion.ServiceReferenceDGAC.AeronaveByPatenteResponse retVal = ((CapaPresentacion.ServiceReferenceDGAC.webservice_dgac)(this)).AeronaveByPatente(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CapaPresentacion.ServiceReferenceDGAC.AeronaveByPatenteResponse> CapaPresentacion.ServiceReferenceDGAC.webservice_dgac.AeronaveByPatenteAsync(CapaPresentacion.ServiceReferenceDGAC.AeronaveByPatenteRequest request) {
            return base.Channel.AeronaveByPatenteAsync(request);
        }
        
        public System.Threading.Tasks.Task<CapaPresentacion.ServiceReferenceDGAC.AeronaveByPatenteResponse> AeronaveByPatenteAsync(string patente) {
            CapaPresentacion.ServiceReferenceDGAC.AeronaveByPatenteRequest inValue = new CapaPresentacion.ServiceReferenceDGAC.AeronaveByPatenteRequest();
            inValue.patente = patente;
            return ((CapaPresentacion.ServiceReferenceDGAC.webservice_dgac)(this)).AeronaveByPatenteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CapaPresentacion.ServiceReferenceDGAC.validarAeronaveByPatenteResponse CapaPresentacion.ServiceReferenceDGAC.webservice_dgac.validarAeronaveByPatente(CapaPresentacion.ServiceReferenceDGAC.validarAeronaveByPatenteRequest request) {
            return base.Channel.validarAeronaveByPatente(request);
        }
        
        public bool validarAeronaveByPatente(string patente) {
            CapaPresentacion.ServiceReferenceDGAC.validarAeronaveByPatenteRequest inValue = new CapaPresentacion.ServiceReferenceDGAC.validarAeronaveByPatenteRequest();
            inValue.patente = patente;
            CapaPresentacion.ServiceReferenceDGAC.validarAeronaveByPatenteResponse retVal = ((CapaPresentacion.ServiceReferenceDGAC.webservice_dgac)(this)).validarAeronaveByPatente(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CapaPresentacion.ServiceReferenceDGAC.validarAeronaveByPatenteResponse> CapaPresentacion.ServiceReferenceDGAC.webservice_dgac.validarAeronaveByPatenteAsync(CapaPresentacion.ServiceReferenceDGAC.validarAeronaveByPatenteRequest request) {
            return base.Channel.validarAeronaveByPatenteAsync(request);
        }
        
        public System.Threading.Tasks.Task<CapaPresentacion.ServiceReferenceDGAC.validarAeronaveByPatenteResponse> validarAeronaveByPatenteAsync(string patente) {
            CapaPresentacion.ServiceReferenceDGAC.validarAeronaveByPatenteRequest inValue = new CapaPresentacion.ServiceReferenceDGAC.validarAeronaveByPatenteRequest();
            inValue.patente = patente;
            return ((CapaPresentacion.ServiceReferenceDGAC.webservice_dgac)(this)).validarAeronaveByPatenteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CapaPresentacion.ServiceReferenceDGAC.fechaAeronavegabilidad_por_patenteResponse CapaPresentacion.ServiceReferenceDGAC.webservice_dgac.fechaAeronavegabilidad_por_patente(CapaPresentacion.ServiceReferenceDGAC.fechaAeronavegabilidad_por_patenteRequest request) {
            return base.Channel.fechaAeronavegabilidad_por_patente(request);
        }
        
        public string fechaAeronavegabilidad_por_patente(string patente) {
            CapaPresentacion.ServiceReferenceDGAC.fechaAeronavegabilidad_por_patenteRequest inValue = new CapaPresentacion.ServiceReferenceDGAC.fechaAeronavegabilidad_por_patenteRequest();
            inValue.patente = patente;
            CapaPresentacion.ServiceReferenceDGAC.fechaAeronavegabilidad_por_patenteResponse retVal = ((CapaPresentacion.ServiceReferenceDGAC.webservice_dgac)(this)).fechaAeronavegabilidad_por_patente(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CapaPresentacion.ServiceReferenceDGAC.fechaAeronavegabilidad_por_patenteResponse> CapaPresentacion.ServiceReferenceDGAC.webservice_dgac.fechaAeronavegabilidad_por_patenteAsync(CapaPresentacion.ServiceReferenceDGAC.fechaAeronavegabilidad_por_patenteRequest request) {
            return base.Channel.fechaAeronavegabilidad_por_patenteAsync(request);
        }
        
        public System.Threading.Tasks.Task<CapaPresentacion.ServiceReferenceDGAC.fechaAeronavegabilidad_por_patenteResponse> fechaAeronavegabilidad_por_patenteAsync(string patente) {
            CapaPresentacion.ServiceReferenceDGAC.fechaAeronavegabilidad_por_patenteRequest inValue = new CapaPresentacion.ServiceReferenceDGAC.fechaAeronavegabilidad_por_patenteRequest();
            inValue.patente = patente;
            return ((CapaPresentacion.ServiceReferenceDGAC.webservice_dgac)(this)).fechaAeronavegabilidad_por_patenteAsync(inValue);
        }
    }
}
