//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMPONENTES
    {
        public COMPONENTES()
        {
            this.COMPONENTES1 = new HashSet<COMPONENTES>();
            this.MANTENIMIENTOS = new HashSet<MANTENIMIENTOS>();
        }
    
        public int IDCOMPONENTE { get; set; }
        public int ESTADO_IDESTADO { get; set; }
        public string NOMBRE { get; set; }
        public Nullable<int> HORAS_USADO { get; set; }
        public Nullable<int> HORAS_MAX_USO { get; set; }
        public Nullable<int> VECES_USADO { get; set; }
        public Nullable<int> MAX_NUM_USOS { get; set; }
        public Nullable<int> COMPONENTES_IDCOMPONENTE { get; set; }
    
        public virtual ICollection<COMPONENTES> COMPONENTES1 { get; set; }
        public virtual COMPONENTES COMPONENTES2 { get; set; }
        public virtual ESTADO ESTADO { get; set; }
        public virtual ICollection<MANTENIMIENTOS> MANTENIMIENTOS { get; set; }
    }
}
