//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class ESTADO
    {
        public ESTADO()
        {
            this.AERONAVES = new HashSet<AERONAVES>();
            this.COMPONENTES = new HashSet<COMPONENTES>();
            this.MANTENIMIENTOS = new HashSet<MANTENIMIENTOS>();
            this.USUARIOS = new HashSet<USUARIOS>();
            this.VUELOS = new HashSet<VUELOS>();
        }
    
        public int IDESTADO { get; set; }
        public string desc { get; set; }
    
        public virtual ICollection<AERONAVES> AERONAVES { get; set; }
        public virtual ICollection<COMPONENTES> COMPONENTES { get; set; }
        public virtual ICollection<MANTENIMIENTOS> MANTENIMIENTOS { get; set; }
        public virtual ICollection<USUARIOS> USUARIOS { get; set; }
        public virtual ICollection<VUELOS> VUELOS { get; set; }
    }
}
