//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class MANTENIMIENTOS
    {
        public int IDMANTENIMIENTO { get; set; }
        public int AERONAVES_IDAERONAVE { get; set; }
        public int ESTADO_IDESTADO { get; set; }
        public string OBS { get; set; }
        public int COMPONENTES_IDCOMPONENTE { get; set; }
    
        public virtual AERONAVES AERONAVES { get; set; }
        public virtual COMPONENTES COMPONENTES { get; set; }
        public virtual ESTADO ESTADO { get; set; }
    }
}
