//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Data.Mapping.EntityViewGenerationAttribute(typeof(Edm_EntityMappingGeneratedViews.ViewsForBaseEntitySetsE2EC4E2216BC85CE118BB317CC1AF4DAC7AD6D4799C11D9A1381A9B85D3E8A71))]

namespace Edm_EntityMappingGeneratedViews
{
    
    
    /// <Summary>
    /// El tipo contiene vistas para EntitySets y AssociationSets que se generaron en tiempo de diseño.
    /// </Summary>
    public sealed class ViewsForBaseEntitySetsE2EC4E2216BC85CE118BB317CC1AF4DAC7AD6D4799C11D9A1381A9B85D3E8A71 : System.Data.Mapping.EntityViewContainer
    {
        
        /// <Summary>
        /// El constructor almacena las vistas para las extensiones y también los valores hash generados basándose en los metadatos y en las vistas y clausuras de asignaciones.
        /// </Summary>
        public ViewsForBaseEntitySetsE2EC4E2216BC85CE118BB317CC1AF4DAC7AD6D4799C11D9A1381A9B85D3E8A71()
        {
            this.EdmEntityContainerName = "EscHalconEntities";
            this.StoreEntityContainerName = "ModelStoreContainer";
            this.HashOverMappingClosure = "24f50576c2954e505f42486a94ff188ef4c574afb4d4f3347ee50fed36ba56d4";
            this.HashOverAllExtentViews = "3b6095269b1d01aa5e850e14198d57d5e8018361e4aee723dfbdedfbaa7ad3e7";
            this.ViewCount = 40;
        }
        
        /// <Summary>
        /// El método devuelve la vista para un índice dado.
        /// </Summary>
        protected override System.Collections.Generic.KeyValuePair<string, string> GetViewAt(int index)
        {
            if ((index == 0))
            {
                return GetView0();
            }
            if ((index == 1))
            {
                return GetView1();
            }
            if ((index == 2))
            {
                return GetView2();
            }
            if ((index == 3))
            {
                return GetView3();
            }
            if ((index == 4))
            {
                return GetView4();
            }
            if ((index == 5))
            {
                return GetView5();
            }
            if ((index == 6))
            {
                return GetView6();
            }
            if ((index == 7))
            {
                return GetView7();
            }
            if ((index == 8))
            {
                return GetView8();
            }
            if ((index == 9))
            {
                return GetView9();
            }
            if ((index == 10))
            {
                return GetView10();
            }
            if ((index == 11))
            {
                return GetView11();
            }
            if ((index == 12))
            {
                return GetView12();
            }
            if ((index == 13))
            {
                return GetView13();
            }
            if ((index == 14))
            {
                return GetView14();
            }
            if ((index == 15))
            {
                return GetView15();
            }
            if ((index == 16))
            {
                return GetView16();
            }
            if ((index == 17))
            {
                return GetView17();
            }
            if ((index == 18))
            {
                return GetView18();
            }
            if ((index == 19))
            {
                return GetView19();
            }
            if ((index == 20))
            {
                return GetView20();
            }
            if ((index == 21))
            {
                return GetView21();
            }
            if ((index == 22))
            {
                return GetView22();
            }
            if ((index == 23))
            {
                return GetView23();
            }
            if ((index == 24))
            {
                return GetView24();
            }
            if ((index == 25))
            {
                return GetView25();
            }
            if ((index == 26))
            {
                return GetView26();
            }
            if ((index == 27))
            {
                return GetView27();
            }
            if ((index == 28))
            {
                return GetView28();
            }
            if ((index == 29))
            {
                return GetView29();
            }
            if ((index == 30))
            {
                return GetView30();
            }
            if ((index == 31))
            {
                return GetView31();
            }
            if ((index == 32))
            {
                return GetView32();
            }
            if ((index == 33))
            {
                return GetView33();
            }
            if ((index == 34))
            {
                return GetView34();
            }
            if ((index == 35))
            {
                return GetView35();
            }
            if ((index == 36))
            {
                return GetView36();
            }
            if ((index == 37))
            {
                return GetView37();
            }
            if ((index == 38))
            {
                return GetView38();
            }
            if ((index == 39))
            {
                return GetView39();
            }
            throw new System.IndexOutOfRangeException();
        }
        
        /// <Summary>
        /// vista devuelta para ModelStoreContainer.ADMINISTRADORES
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView0()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("ModelStoreContainer.ADMINISTRADORES", @"
    SELECT VALUE -- Constructing ADMINISTRADORES
        [Model.Store.ADMINISTRADORES](T1.ADMINISTRADORES_IDUSUARIO, T1.ADMINISTRADORES_RUT)
    FROM (
        SELECT 
            T.IDUSUARIO AS ADMINISTRADORES_IDUSUARIO, 
            T.RUT AS ADMINISTRADORES_RUT, 
            True AS _from0
        FROM EscHalconEntities.ADMINISTRADORES AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// vista devuelta para ModelStoreContainer.AERONAVES
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView1()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("ModelStoreContainer.AERONAVES", "\r\n    SELECT VALUE -- Constructing AERONAVES\r\n        [Model.Store.AERONAVES](T1." +
                    "AERONAVES_IDAERONAVE, T1.[AERONAVES.TIPO_AERONAVE_IDTIPO_AERONAVE], T1.[AERONAVE" +
                    "S.ESTADO_IDESTADO], T1.[AERONAVES.FABRICANTES_AERO_IDFABRICANTE], T1.[AERONAVES." +
                    "MODELOS_AERO_IDMODELO], T1.[AERONAVES.HORAS_VOLADAS], T1.[AERONAVES.CANT_MAX_HOR" +
                    "AS], T1.AERONAVES_PATENTE, T1.[AERONAVES.ANIO_FAB], T1.[AERONAVES.CANT_MAX_PILOT" +
                    "OS], T1.[AERONAVES.FECHA_INSPECCION_ANUAL], T1.[AERONAVES.CAP_LITROS], T1.AERONA" +
                    "VES_MOTOR, T1.AERONAVES_RUEDAS, T1.[AERONAVES.CANT_HELICES], T1.[AERONAVES.CANT_" +
                    "TURBINAS])\r\n    FROM (\r\n        SELECT \r\n            T.IDAERONAVE AS AERONAVES_I" +
                    "DAERONAVE, \r\n            T.TIPO_AERONAVE_IDTIPO_AERONAVE AS [AERONAVES.TIPO_AERO" +
                    "NAVE_IDTIPO_AERONAVE], \r\n            T.ESTADO_IDESTADO AS [AERONAVES.ESTADO_IDES" +
                    "TADO], \r\n            T.FABRICANTES_AERO_IDFABRICANTE AS [AERONAVES.FABRICANTES_A" +
                    "ERO_IDFABRICANTE], \r\n            T.MODELOS_AERO_IDMODELO AS [AERONAVES.MODELOS_A" +
                    "ERO_IDMODELO], \r\n            T.HORAS_VOLADAS AS [AERONAVES.HORAS_VOLADAS], \r\n   " +
                    "         T.CANT_MAX_HORAS AS [AERONAVES.CANT_MAX_HORAS], \r\n            T.PATENTE" +
                    " AS AERONAVES_PATENTE, \r\n            T.ANIO_FAB AS [AERONAVES.ANIO_FAB], \r\n     " +
                    "       T.CANT_MAX_PILOTOS AS [AERONAVES.CANT_MAX_PILOTOS], \r\n            T.FECHA" +
                    "_INSPECCION_ANUAL AS [AERONAVES.FECHA_INSPECCION_ANUAL], \r\n            T.CAP_LIT" +
                    "ROS AS [AERONAVES.CAP_LITROS], \r\n            T.MOTOR AS AERONAVES_MOTOR, \r\n     " +
                    "       T.RUEDAS AS AERONAVES_RUEDAS, \r\n            T.CANT_HELICES AS [AERONAVES." +
                    "CANT_HELICES], \r\n            T.CANT_TURBINAS AS [AERONAVES.CANT_TURBINAS], \r\n   " +
                    "         True AS _from0\r\n        FROM EscHalconEntities.AERONAVES AS T\r\n    ) AS" +
                    " T1");
        }
        
        /// <Summary>
        /// vista devuelta para ModelStoreContainer.BITACORAS_VUELOS
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView2()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("ModelStoreContainer.BITACORAS_VUELOS", @"
    SELECT VALUE -- Constructing BITACORAS_VUELOS
        [Model.Store.BITACORAS_VUELOS](T1.[BITACORAS_VUELOS.IDBITACORA_VUELO], T1.[BITACORAS_VUELOS.VUELOS_IDVUELO], T1.[BITACORAS_VUELOS.HORA_INCIDENTE], T1.[BITACORAS_VUELOS.desc])
    FROM (
        SELECT 
            T.IDBITACORA_VUELO AS [BITACORAS_VUELOS.IDBITACORA_VUELO], 
            T.VUELOS_IDVUELO AS [BITACORAS_VUELOS.VUELOS_IDVUELO], 
            T.HORA_INCIDENTE AS [BITACORAS_VUELOS.HORA_INCIDENTE], 
            T.[desc] AS [BITACORAS_VUELOS.desc], 
            True AS _from0
        FROM EscHalconEntities.BITACORAS_VUELOS AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// vista devuelta para ModelStoreContainer.COMPONENTES
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView3()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("ModelStoreContainer.COMPONENTES", @"
    SELECT VALUE -- Constructing COMPONENTES
        [Model.Store.COMPONENTES](T1.COMPONENTES_IDCOMPONENTE, T1.[COMPONENTES.ESTADO_IDESTADO], T1.COMPONENTES_NOMBRE, T1.[COMPONENTES.HORAS_USADO], T1.[COMPONENTES.HORAS_MAX_USO], T1.[COMPONENTES.VECES_USADO], T1.[COMPONENTES.MAX_NUM_USOS], T1.[COMPONENTES.COMPONENTES_IDCOMPONENTE])
    FROM (
        SELECT 
            T.IDCOMPONENTE AS COMPONENTES_IDCOMPONENTE, 
            T.ESTADO_IDESTADO AS [COMPONENTES.ESTADO_IDESTADO], 
            T.NOMBRE AS COMPONENTES_NOMBRE, 
            T.HORAS_USADO AS [COMPONENTES.HORAS_USADO], 
            T.HORAS_MAX_USO AS [COMPONENTES.HORAS_MAX_USO], 
            T.VECES_USADO AS [COMPONENTES.VECES_USADO], 
            T.MAX_NUM_USOS AS [COMPONENTES.MAX_NUM_USOS], 
            T.COMPONENTES_IDCOMPONENTE AS [COMPONENTES.COMPONENTES_IDCOMPONENTE], 
            True AS _from0
        FROM EscHalconEntities.COMPONENTES AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// vista devuelta para ModelStoreContainer.CONDICION
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView4()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("ModelStoreContainer.CONDICION", @"
    SELECT VALUE -- Constructing CONDICION
        [Model.Store.CONDICION](T1.[CONDICION.IDCONDICION_VUELO], T1.CONDICION_desc)
    FROM (
        SELECT 
            T.IDCONDICION_VUELO AS [CONDICION.IDCONDICION_VUELO], 
            T.[desc] AS CONDICION_desc, 
            True AS _from0
        FROM EscHalconEntities.CONDICION AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// vista devuelta para ModelStoreContainer.CONSULTORES
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView5()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("ModelStoreContainer.CONSULTORES", @"
    SELECT VALUE -- Constructing CONSULTORES
        [Model.Store.CONSULTORES](T1.CONSULTORES_IDUSUARIO, T1.CONSULTORES_RUT)
    FROM (
        SELECT 
            T.IDUSUARIO AS CONSULTORES_IDUSUARIO, 
            T.RUT AS CONSULTORES_RUT, 
            True AS _from0
        FROM EscHalconEntities.CONSULTORES AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// vista devuelta para ModelStoreContainer.CREDENCIALES
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView6()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("ModelStoreContainer.CREDENCIALES", @"
    SELECT VALUE -- Constructing CREDENCIALES
        [Model.Store.CREDENCIALES](T1.CREDENCIALES_IDCREDENCIAL, T1.CREDENCIALES_PW, T1.[CREDENCIALES.USUARIOS_IDUSUARIO], T1.CREDENCIALES_RUT)
    FROM (
        SELECT 
            T.IDCREDENCIAL AS CREDENCIALES_IDCREDENCIAL, 
            T.PW AS CREDENCIALES_PW, 
            T.USUARIOS_IDUSUARIO AS [CREDENCIALES.USUARIOS_IDUSUARIO], 
            T.RUT AS CREDENCIALES_RUT, 
            True AS _from0
        FROM EscHalconEntities.CREDENCIALES AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// vista devuelta para ModelStoreContainer.ESTADO
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView7()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("ModelStoreContainer.ESTADO", @"
    SELECT VALUE -- Constructing ESTADO
        [Model.Store.ESTADO](T1.ESTADO_IDESTADO, T1.ESTADO_desc)
    FROM (
        SELECT 
            T.IDESTADO AS ESTADO_IDESTADO, 
            T.[desc] AS ESTADO_desc, 
            True AS _from0
        FROM EscHalconEntities.ESTADO AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// vista devuelta para ModelStoreContainer.FABRICANTES_AERO
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView8()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("ModelStoreContainer.FABRICANTES_AERO", @"
    SELECT VALUE -- Constructing FABRICANTES_AERO
        [Model.Store.FABRICANTES_AERO](T1.[FABRICANTES_AERO.IDFABRICANTE], T1.[FABRICANTES_AERO.NOMBRE_FAB])
    FROM (
        SELECT 
            T.IDFABRICANTE AS [FABRICANTES_AERO.IDFABRICANTE], 
            T.NOMBRE_FAB AS [FABRICANTES_AERO.NOMBRE_FAB], 
            True AS _from0
        FROM EscHalconEntities.FABRICANTES_AERO AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// vista devuelta para ModelStoreContainer.MEDICINAS
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView9()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("ModelStoreContainer.MEDICINAS", @"
    SELECT VALUE -- Constructing MEDICINAS
        [Model.Store.MEDICINAS](T1.MEDICINAS_IDMEDICINA, T1.MEDICINAS_NOMBRE, T1.MEDICINAS_DOSIS)
    FROM (
        SELECT 
            T.IDMEDICINA AS MEDICINAS_IDMEDICINA, 
            T.NOMBRE AS MEDICINAS_NOMBRE, 
            T.DOSIS AS MEDICINAS_DOSIS, 
            True AS _from0
        FROM EscHalconEntities.MEDICINAS AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// vista devuelta para ModelStoreContainer.MODELOS_AERO
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView10()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("ModelStoreContainer.MODELOS_AERO", @"
    SELECT VALUE -- Constructing MODELOS_AERO
        [Model.Store.MODELOS_AERO](T1.[MODELOS_AERO.IDMODELO], T1.[MODELOS_AERO.MODELO_AERONAVE])
    FROM (
        SELECT 
            T.IDMODELO AS [MODELOS_AERO.IDMODELO], 
            T.MODELO_AERONAVE AS [MODELOS_AERO.MODELO_AERONAVE], 
            True AS _from0
        FROM EscHalconEntities.MODELOS_AERO AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// vista devuelta para ModelStoreContainer.OPERARIOS
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView11()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("ModelStoreContainer.OPERARIOS", @"
    SELECT VALUE -- Constructing OPERARIOS
        [Model.Store.OPERARIOS](T1.OPERARIOS_IDUSUARIO, T1.OPERARIOS_RUT)
    FROM (
        SELECT 
            T.IDUSUARIO AS OPERARIOS_IDUSUARIO, 
            T.RUT AS OPERARIOS_RUT, 
            True AS _from0
        FROM EscHalconEntities.OPERARIOS AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// vista devuelta para ModelStoreContainer.PILOTOS
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView12()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("ModelStoreContainer.PILOTOS", @"
    SELECT VALUE -- Constructing PILOTOS
        [Model.Store.PILOTOS](T1.PILOTOS_IDUSUARIO, T1.[PILOTOS.HORAS_VOLADAS], T1.PILOTOS_RUT)
    FROM (
        SELECT 
            T.IDUSUARIO AS PILOTOS_IDUSUARIO, 
            T.HORAS_VOLADAS AS [PILOTOS.HORAS_VOLADAS], 
            T.RUT AS PILOTOS_RUT, 
            True AS _from0
        FROM EscHalconEntities.PILOTOS AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// vista devuelta para ModelStoreContainer.TIPO_AERONAVE
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView13()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("ModelStoreContainer.TIPO_AERONAVE", @"
    SELECT VALUE -- Constructing TIPO_AERONAVE
        [Model.Store.TIPO_AERONAVE](T1.[TIPO_AERONAVE.IDTIPO_AERONAVE], T1.[TIPO_AERONAVE.desc])
    FROM (
        SELECT 
            T.IDTIPO_AERONAVE AS [TIPO_AERONAVE.IDTIPO_AERONAVE], 
            T.[desc] AS [TIPO_AERONAVE.desc], 
            True AS _from0
        FROM EscHalconEntities.TIPO_AERONAVE AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// vista devuelta para ModelStoreContainer.USUARIOS
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView14()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("ModelStoreContainer.USUARIOS", @"
    SELECT VALUE -- Constructing USUARIOS
        [Model.Store.USUARIOS](T1.USUARIOS_IDUSUARIO, T1.[USUARIOS.ESTADO_IDESTADO], T1.USUARIOS_RUT, T1.USUARIOS_NOMBRES, T1.[USUARIOS.AP_PATERNO], T1.[USUARIOS.AP_MATERNO], T1.USUARIOS_DOMICILIO, T1.[USUARIOS.TEL_CEL], T1.[USUARIOS.TEL_FIJO], T1.USUARIOS_CORREO)
    FROM (
        SELECT 
            T.IDUSUARIO AS USUARIOS_IDUSUARIO, 
            T.ESTADO_IDESTADO AS [USUARIOS.ESTADO_IDESTADO], 
            T.RUT AS USUARIOS_RUT, 
            T.NOMBRES AS USUARIOS_NOMBRES, 
            T.AP_PATERNO AS [USUARIOS.AP_PATERNO], 
            T.AP_MATERNO AS [USUARIOS.AP_MATERNO], 
            T.DOMICILIO AS USUARIOS_DOMICILIO, 
            T.TEL_CEL AS [USUARIOS.TEL_CEL], 
            T.TEL_FIJO AS [USUARIOS.TEL_FIJO], 
            T.CORREO AS USUARIOS_CORREO, 
            True AS _from0
        FROM EscHalconEntities.USUARIOS AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// vista devuelta para ModelStoreContainer.VUELOS
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView15()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("ModelStoreContainer.VUELOS", @"
    SELECT VALUE -- Constructing VUELOS
        [Model.Store.VUELOS](T1.VUELOS_IDVUELO, T1.[VUELOS.ESTADO_IDESTADO], T1.[VUELOS.AERONAVES_IDAERONAVE], T1.[VUELOS.HORAS_ESTIMADAS], T1.VUELOS_MISION, T1.[VUELOS.FECHAHORA_INICIO], T1.[VUELOS.CONDICION_IDCONDICION_VUELO])
    FROM (
        SELECT 
            T.IDVUELO AS VUELOS_IDVUELO, 
            T.ESTADO_IDESTADO AS [VUELOS.ESTADO_IDESTADO], 
            T.AERONAVES_IDAERONAVE AS [VUELOS.AERONAVES_IDAERONAVE], 
            T.HORAS_ESTIMADAS AS [VUELOS.HORAS_ESTIMADAS], 
            T.MISION AS VUELOS_MISION, 
            T.FECHAHORA_INICIO AS [VUELOS.FECHAHORA_INICIO], 
            T.CONDICION_IDCONDICION_VUELO AS [VUELOS.CONDICION_IDCONDICION_VUELO], 
            True AS _from0
        FROM EscHalconEntities.VUELOS AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// vista devuelta para ModelStoreContainer.MEDICINAS_PILOTOS
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView16()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("ModelStoreContainer.MEDICINAS_PILOTOS", @"
    SELECT VALUE -- Constructing MEDICINAS_PILOTOS
        [Model.Store.MEDICINAS_PILOTOS](T1.[MEDICINAS_PILOTOS.PILOTOS_IDUSUARIO], T1.[MEDICINAS_PILOTOS.PILOTOS_RUT], T1.[MEDICINAS_PILOTOS.MEDICINAS_IDMEDICINA])
    FROM (
        SELECT 
            Key(T.PILOTOS).IDUSUARIO AS [MEDICINAS_PILOTOS.PILOTOS_IDUSUARIO], 
            Key(T.PILOTOS).RUT AS [MEDICINAS_PILOTOS.PILOTOS_RUT], 
            Key(T.MEDICINAS).IDMEDICINA AS [MEDICINAS_PILOTOS.MEDICINAS_IDMEDICINA], 
            True AS _from0
        FROM EscHalconEntities.MEDICINAS_PILOTOS AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// vista devuelta para ModelStoreContainer.PILOTOS_VUELOS
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView17()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("ModelStoreContainer.PILOTOS_VUELOS", @"
    SELECT VALUE -- Constructing PILOTOS_VUELOS
        [Model.Store.PILOTOS_VUELOS](T1.[PILOTOS_VUELOS.PILOTOS_IDUSUARIO], T1.[PILOTOS_VUELOS.PILOTOS_RUT], T1.[PILOTOS_VUELOS.VUELOS_IDVUELO])
    FROM (
        SELECT 
            Key(T.PILOTOS).IDUSUARIO AS [PILOTOS_VUELOS.PILOTOS_IDUSUARIO], 
            Key(T.PILOTOS).RUT AS [PILOTOS_VUELOS.PILOTOS_RUT], 
            Key(T.VUELOS).IDVUELO AS [PILOTOS_VUELOS.VUELOS_IDVUELO], 
            True AS _from0
        FROM EscHalconEntities.PILOTOS_VUELOS AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// vista devuelta para EscHalconEntities.ADMINISTRADORES
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView18()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("EscHalconEntities.ADMINISTRADORES", @"
    SELECT VALUE -- Constructing ADMINISTRADORES
        [Model.ADMINISTRADORES](T1.ADMINISTRADORES_IDUSUARIO, T1.ADMINISTRADORES_RUT)
    FROM (
        SELECT 
            T.IDUSUARIO AS ADMINISTRADORES_IDUSUARIO, 
            T.RUT AS ADMINISTRADORES_RUT, 
            True AS _from0
        FROM ModelStoreContainer.ADMINISTRADORES AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// vista devuelta para EscHalconEntities.AERONAVES
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView19()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("EscHalconEntities.AERONAVES", "\r\n    SELECT VALUE -- Constructing AERONAVES\r\n        [Model.AERONAVES](T1.AERONA" +
                    "VES_IDAERONAVE, T1.[AERONAVES.TIPO_AERONAVE_IDTIPO_AERONAVE], T1.[AERONAVES.ESTA" +
                    "DO_IDESTADO], T1.[AERONAVES.FABRICANTES_AERO_IDFABRICANTE], T1.[AERONAVES.MODELO" +
                    "S_AERO_IDMODELO], T1.[AERONAVES.HORAS_VOLADAS], T1.[AERONAVES.CANT_MAX_HORAS], T" +
                    "1.AERONAVES_PATENTE, T1.[AERONAVES.ANIO_FAB], T1.[AERONAVES.CANT_MAX_PILOTOS], T" +
                    "1.[AERONAVES.FECHA_INSPECCION_ANUAL], T1.[AERONAVES.CAP_LITROS], T1.AERONAVES_MO" +
                    "TOR, T1.AERONAVES_RUEDAS, T1.[AERONAVES.CANT_HELICES], T1.[AERONAVES.CANT_TURBIN" +
                    "AS])\r\n    FROM (\r\n        SELECT \r\n            T.IDAERONAVE AS AERONAVES_IDAERON" +
                    "AVE, \r\n            T.TIPO_AERONAVE_IDTIPO_AERONAVE AS [AERONAVES.TIPO_AERONAVE_I" +
                    "DTIPO_AERONAVE], \r\n            T.ESTADO_IDESTADO AS [AERONAVES.ESTADO_IDESTADO]," +
                    " \r\n            T.FABRICANTES_AERO_IDFABRICANTE AS [AERONAVES.FABRICANTES_AERO_ID" +
                    "FABRICANTE], \r\n            T.MODELOS_AERO_IDMODELO AS [AERONAVES.MODELOS_AERO_ID" +
                    "MODELO], \r\n            T.HORAS_VOLADAS AS [AERONAVES.HORAS_VOLADAS], \r\n         " +
                    "   T.CANT_MAX_HORAS AS [AERONAVES.CANT_MAX_HORAS], \r\n            T.PATENTE AS AE" +
                    "RONAVES_PATENTE, \r\n            T.ANIO_FAB AS [AERONAVES.ANIO_FAB], \r\n           " +
                    " T.CANT_MAX_PILOTOS AS [AERONAVES.CANT_MAX_PILOTOS], \r\n            T.FECHA_INSPE" +
                    "CCION_ANUAL AS [AERONAVES.FECHA_INSPECCION_ANUAL], \r\n            T.CAP_LITROS AS" +
                    " [AERONAVES.CAP_LITROS], \r\n            T.MOTOR AS AERONAVES_MOTOR, \r\n           " +
                    " T.RUEDAS AS AERONAVES_RUEDAS, \r\n            T.CANT_HELICES AS [AERONAVES.CANT_H" +
                    "ELICES], \r\n            T.CANT_TURBINAS AS [AERONAVES.CANT_TURBINAS], \r\n         " +
                    "   True AS _from0\r\n        FROM ModelStoreContainer.AERONAVES AS T\r\n    ) AS T1");
        }
        
        /// <Summary>
        /// vista devuelta para EscHalconEntities.BITACORAS_VUELOS
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView20()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("EscHalconEntities.BITACORAS_VUELOS", @"
    SELECT VALUE -- Constructing BITACORAS_VUELOS
        [Model.BITACORAS_VUELOS](T1.[BITACORAS_VUELOS.IDBITACORA_VUELO], T1.[BITACORAS_VUELOS.VUELOS_IDVUELO], T1.[BITACORAS_VUELOS.HORA_INCIDENTE], T1.[BITACORAS_VUELOS.desc])
    FROM (
        SELECT 
            T.IDBITACORA_VUELO AS [BITACORAS_VUELOS.IDBITACORA_VUELO], 
            T.VUELOS_IDVUELO AS [BITACORAS_VUELOS.VUELOS_IDVUELO], 
            T.HORA_INCIDENTE AS [BITACORAS_VUELOS.HORA_INCIDENTE], 
            T.[desc] AS [BITACORAS_VUELOS.desc], 
            True AS _from0
        FROM ModelStoreContainer.BITACORAS_VUELOS AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// vista devuelta para EscHalconEntities.COMPONENTES
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView21()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("EscHalconEntities.COMPONENTES", @"
    SELECT VALUE -- Constructing COMPONENTES
        [Model.COMPONENTES](T1.COMPONENTES_IDCOMPONENTE, T1.[COMPONENTES.ESTADO_IDESTADO], T1.COMPONENTES_NOMBRE, T1.[COMPONENTES.HORAS_USADO], T1.[COMPONENTES.HORAS_MAX_USO], T1.[COMPONENTES.VECES_USADO], T1.[COMPONENTES.MAX_NUM_USOS], T1.[COMPONENTES.COMPONENTES_IDCOMPONENTE])
    FROM (
        SELECT 
            T.IDCOMPONENTE AS COMPONENTES_IDCOMPONENTE, 
            T.ESTADO_IDESTADO AS [COMPONENTES.ESTADO_IDESTADO], 
            T.NOMBRE AS COMPONENTES_NOMBRE, 
            T.HORAS_USADO AS [COMPONENTES.HORAS_USADO], 
            T.HORAS_MAX_USO AS [COMPONENTES.HORAS_MAX_USO], 
            T.VECES_USADO AS [COMPONENTES.VECES_USADO], 
            T.MAX_NUM_USOS AS [COMPONENTES.MAX_NUM_USOS], 
            T.COMPONENTES_IDCOMPONENTE AS [COMPONENTES.COMPONENTES_IDCOMPONENTE], 
            True AS _from0
        FROM ModelStoreContainer.COMPONENTES AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// vista devuelta para EscHalconEntities.CONDICION
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView22()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("EscHalconEntities.CONDICION", @"
    SELECT VALUE -- Constructing CONDICION
        [Model.CONDICION](T1.[CONDICION.IDCONDICION_VUELO], T1.CONDICION_desc)
    FROM (
        SELECT 
            T.IDCONDICION_VUELO AS [CONDICION.IDCONDICION_VUELO], 
            T.[desc] AS CONDICION_desc, 
            True AS _from0
        FROM ModelStoreContainer.CONDICION AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// vista devuelta para EscHalconEntities.CONSULTORES
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView23()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("EscHalconEntities.CONSULTORES", @"
    SELECT VALUE -- Constructing CONSULTORES
        [Model.CONSULTORES](T1.CONSULTORES_IDUSUARIO, T1.CONSULTORES_RUT)
    FROM (
        SELECT 
            T.IDUSUARIO AS CONSULTORES_IDUSUARIO, 
            T.RUT AS CONSULTORES_RUT, 
            True AS _from0
        FROM ModelStoreContainer.CONSULTORES AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// vista devuelta para EscHalconEntities.CREDENCIALES
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView24()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("EscHalconEntities.CREDENCIALES", @"
    SELECT VALUE -- Constructing CREDENCIALES
        [Model.CREDENCIALES](T1.CREDENCIALES_IDCREDENCIAL, T1.CREDENCIALES_PW, T1.[CREDENCIALES.USUARIOS_IDUSUARIO], T1.CREDENCIALES_RUT)
    FROM (
        SELECT 
            T.IDCREDENCIAL AS CREDENCIALES_IDCREDENCIAL, 
            T.PW AS CREDENCIALES_PW, 
            T.USUARIOS_IDUSUARIO AS [CREDENCIALES.USUARIOS_IDUSUARIO], 
            T.RUT AS CREDENCIALES_RUT, 
            True AS _from0
        FROM ModelStoreContainer.CREDENCIALES AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// vista devuelta para EscHalconEntities.ESTADO
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView25()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("EscHalconEntities.ESTADO", @"
    SELECT VALUE -- Constructing ESTADO
        [Model.ESTADO](T1.ESTADO_IDESTADO, T1.ESTADO_desc)
    FROM (
        SELECT 
            T.IDESTADO AS ESTADO_IDESTADO, 
            T.[desc] AS ESTADO_desc, 
            True AS _from0
        FROM ModelStoreContainer.ESTADO AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// vista devuelta para EscHalconEntities.FABRICANTES_AERO
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView26()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("EscHalconEntities.FABRICANTES_AERO", @"
    SELECT VALUE -- Constructing FABRICANTES_AERO
        [Model.FABRICANTES_AERO](T1.[FABRICANTES_AERO.IDFABRICANTE], T1.[FABRICANTES_AERO.NOMBRE_FAB])
    FROM (
        SELECT 
            T.IDFABRICANTE AS [FABRICANTES_AERO.IDFABRICANTE], 
            T.NOMBRE_FAB AS [FABRICANTES_AERO.NOMBRE_FAB], 
            True AS _from0
        FROM ModelStoreContainer.FABRICANTES_AERO AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// vista devuelta para EscHalconEntities.MEDICINAS
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView27()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("EscHalconEntities.MEDICINAS", @"
    SELECT VALUE -- Constructing MEDICINAS
        [Model.MEDICINAS](T1.MEDICINAS_IDMEDICINA, T1.MEDICINAS_NOMBRE, T1.MEDICINAS_DOSIS)
    FROM (
        SELECT 
            T.IDMEDICINA AS MEDICINAS_IDMEDICINA, 
            T.NOMBRE AS MEDICINAS_NOMBRE, 
            T.DOSIS AS MEDICINAS_DOSIS, 
            True AS _from0
        FROM ModelStoreContainer.MEDICINAS AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// vista devuelta para EscHalconEntities.MODELOS_AERO
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView28()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("EscHalconEntities.MODELOS_AERO", @"
    SELECT VALUE -- Constructing MODELOS_AERO
        [Model.MODELOS_AERO](T1.[MODELOS_AERO.IDMODELO], T1.[MODELOS_AERO.MODELO_AERONAVE])
    FROM (
        SELECT 
            T.IDMODELO AS [MODELOS_AERO.IDMODELO], 
            T.MODELO_AERONAVE AS [MODELOS_AERO.MODELO_AERONAVE], 
            True AS _from0
        FROM ModelStoreContainer.MODELOS_AERO AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// vista devuelta para EscHalconEntities.OPERARIOS
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView29()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("EscHalconEntities.OPERARIOS", @"
    SELECT VALUE -- Constructing OPERARIOS
        [Model.OPERARIOS](T1.OPERARIOS_IDUSUARIO, T1.OPERARIOS_RUT)
    FROM (
        SELECT 
            T.IDUSUARIO AS OPERARIOS_IDUSUARIO, 
            T.RUT AS OPERARIOS_RUT, 
            True AS _from0
        FROM ModelStoreContainer.OPERARIOS AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// vista devuelta para EscHalconEntities.PILOTOS
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView30()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("EscHalconEntities.PILOTOS", @"
    SELECT VALUE -- Constructing PILOTOS
        [Model.PILOTOS](T1.PILOTOS_IDUSUARIO, T1.[PILOTOS.HORAS_VOLADAS], T1.PILOTOS_RUT)
    FROM (
        SELECT 
            T.IDUSUARIO AS PILOTOS_IDUSUARIO, 
            T.HORAS_VOLADAS AS [PILOTOS.HORAS_VOLADAS], 
            T.RUT AS PILOTOS_RUT, 
            True AS _from0
        FROM ModelStoreContainer.PILOTOS AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// vista devuelta para EscHalconEntities.TIPO_AERONAVE
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView31()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("EscHalconEntities.TIPO_AERONAVE", @"
    SELECT VALUE -- Constructing TIPO_AERONAVE
        [Model.TIPO_AERONAVE](T1.[TIPO_AERONAVE.IDTIPO_AERONAVE], T1.[TIPO_AERONAVE.desc])
    FROM (
        SELECT 
            T.IDTIPO_AERONAVE AS [TIPO_AERONAVE.IDTIPO_AERONAVE], 
            T.[desc] AS [TIPO_AERONAVE.desc], 
            True AS _from0
        FROM ModelStoreContainer.TIPO_AERONAVE AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// vista devuelta para EscHalconEntities.USUARIOS
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView32()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("EscHalconEntities.USUARIOS", @"
    SELECT VALUE -- Constructing USUARIOS
        [Model.USUARIOS](T1.USUARIOS_IDUSUARIO, T1.[USUARIOS.ESTADO_IDESTADO], T1.USUARIOS_RUT, T1.USUARIOS_NOMBRES, T1.[USUARIOS.AP_PATERNO], T1.[USUARIOS.AP_MATERNO], T1.USUARIOS_DOMICILIO, T1.[USUARIOS.TEL_CEL], T1.[USUARIOS.TEL_FIJO], T1.USUARIOS_CORREO)
    FROM (
        SELECT 
            T.IDUSUARIO AS USUARIOS_IDUSUARIO, 
            T.ESTADO_IDESTADO AS [USUARIOS.ESTADO_IDESTADO], 
            T.RUT AS USUARIOS_RUT, 
            T.NOMBRES AS USUARIOS_NOMBRES, 
            T.AP_PATERNO AS [USUARIOS.AP_PATERNO], 
            T.AP_MATERNO AS [USUARIOS.AP_MATERNO], 
            T.DOMICILIO AS USUARIOS_DOMICILIO, 
            T.TEL_CEL AS [USUARIOS.TEL_CEL], 
            T.TEL_FIJO AS [USUARIOS.TEL_FIJO], 
            T.CORREO AS USUARIOS_CORREO, 
            True AS _from0
        FROM ModelStoreContainer.USUARIOS AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// vista devuelta para EscHalconEntities.VUELOS
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView33()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("EscHalconEntities.VUELOS", @"
    SELECT VALUE -- Constructing VUELOS
        [Model.VUELOS](T1.VUELOS_IDVUELO, T1.[VUELOS.ESTADO_IDESTADO], T1.[VUELOS.AERONAVES_IDAERONAVE], T1.[VUELOS.HORAS_ESTIMADAS], T1.VUELOS_MISION, T1.[VUELOS.FECHAHORA_INICIO], T1.[VUELOS.CONDICION_IDCONDICION_VUELO])
    FROM (
        SELECT 
            T.IDVUELO AS VUELOS_IDVUELO, 
            T.ESTADO_IDESTADO AS [VUELOS.ESTADO_IDESTADO], 
            T.AERONAVES_IDAERONAVE AS [VUELOS.AERONAVES_IDAERONAVE], 
            T.HORAS_ESTIMADAS AS [VUELOS.HORAS_ESTIMADAS], 
            T.MISION AS VUELOS_MISION, 
            T.FECHAHORA_INICIO AS [VUELOS.FECHAHORA_INICIO], 
            T.CONDICION_IDCONDICION_VUELO AS [VUELOS.CONDICION_IDCONDICION_VUELO], 
            True AS _from0
        FROM ModelStoreContainer.VUELOS AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// vista devuelta para EscHalconEntities.MEDICINAS_PILOTOS
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView34()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("EscHalconEntities.MEDICINAS_PILOTOS", @"
    SELECT VALUE -- Constructing MEDICINAS_PILOTOS
        [Model.MEDICINAS_PILOTOS](T3.[MEDICINAS_PILOTOS.MEDICINAS], T3.[MEDICINAS_PILOTOS.PILOTOS])
    FROM (
        SELECT -- Constructing MEDICINAS
            CreateRef(EscHalconEntities.MEDICINAS, row(T2.[MEDICINAS_PILOTOS.MEDICINAS.IDMEDICINA]), [Model.MEDICINAS]) AS [MEDICINAS_PILOTOS.MEDICINAS], 
            T2.[MEDICINAS_PILOTOS.PILOTOS]
        FROM (
            SELECT -- Constructing PILOTOS
                T1.[MEDICINAS_PILOTOS.MEDICINAS.IDMEDICINA], 
                CreateRef(EscHalconEntities.PILOTOS, row(T1.[MEDICINAS_PILOTOS.PILOTOS.IDUSUARIO], T1.[MEDICINAS_PILOTOS.PILOTOS.RUT]), [Model.PILOTOS]) AS [MEDICINAS_PILOTOS.PILOTOS]
            FROM (
                SELECT 
                    T.MEDICINAS_IDMEDICINA AS [MEDICINAS_PILOTOS.MEDICINAS.IDMEDICINA], 
                    T.PILOTOS_IDUSUARIO AS [MEDICINAS_PILOTOS.PILOTOS.IDUSUARIO], 
                    T.PILOTOS_RUT AS [MEDICINAS_PILOTOS.PILOTOS.RUT], 
                    True AS _from0
                FROM ModelStoreContainer.MEDICINAS_PILOTOS AS T
            ) AS T1
        ) AS T2
    ) AS T3");
        }
        
        /// <Summary>
        /// vista devuelta para EscHalconEntities.PILOTOS_VUELOS
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView35()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("EscHalconEntities.PILOTOS_VUELOS", @"
    SELECT VALUE -- Constructing PILOTOS_VUELOS
        [Model.PILOTOS_VUELOS](T3.[PILOTOS_VUELOS.PILOTOS], T3.[PILOTOS_VUELOS.VUELOS])
    FROM (
        SELECT -- Constructing PILOTOS
            CreateRef(EscHalconEntities.PILOTOS, row(T2.[PILOTOS_VUELOS.PILOTOS.IDUSUARIO], T2.[PILOTOS_VUELOS.PILOTOS.RUT]), [Model.PILOTOS]) AS [PILOTOS_VUELOS.PILOTOS], 
            T2.[PILOTOS_VUELOS.VUELOS]
        FROM (
            SELECT -- Constructing VUELOS
                T1.[PILOTOS_VUELOS.PILOTOS.IDUSUARIO], 
                T1.[PILOTOS_VUELOS.PILOTOS.RUT], 
                CreateRef(EscHalconEntities.VUELOS, row(T1.[PILOTOS_VUELOS.VUELOS.IDVUELO]), [Model.VUELOS]) AS [PILOTOS_VUELOS.VUELOS]
            FROM (
                SELECT 
                    T.PILOTOS_IDUSUARIO AS [PILOTOS_VUELOS.PILOTOS.IDUSUARIO], 
                    T.PILOTOS_RUT AS [PILOTOS_VUELOS.PILOTOS.RUT], 
                    T.VUELOS_IDVUELO AS [PILOTOS_VUELOS.VUELOS.IDVUELO], 
                    True AS _from0
                FROM ModelStoreContainer.PILOTOS_VUELOS AS T
            ) AS T1
        ) AS T2
    ) AS T3");
        }
        
        /// <Summary>
        /// vista devuelta para ModelStoreContainer.FALLAS_BBDD
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView36()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("ModelStoreContainer.FALLAS_BBDD", @"
    SELECT VALUE -- Constructing FALLAS_BBDD
        [Model.Store.FALLAS_BBDD](T1.[FALLAS_BBDD.IDFALLAS_BBDD], T1.[FALLAS_BBDD.FECHA], T1.[FALLAS_BBDD.ERROR])
    FROM (
        SELECT 
            T.IDFALLAS_BBDD AS [FALLAS_BBDD.IDFALLAS_BBDD], 
            T.FECHA AS [FALLAS_BBDD.FECHA], 
            T.ERROR AS [FALLAS_BBDD.ERROR], 
            True AS _from0
        FROM EscHalconEntities.FALLAS_BBDD AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// vista devuelta para EscHalconEntities.FALLAS_BBDD
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView37()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("EscHalconEntities.FALLAS_BBDD", @"
    SELECT VALUE -- Constructing FALLAS_BBDD
        [Model.FALLAS_BBDD](T1.[FALLAS_BBDD.IDFALLAS_BBDD], T1.[FALLAS_BBDD.FECHA], T1.[FALLAS_BBDD.ERROR])
    FROM (
        SELECT 
            T.IDFALLAS_BBDD AS [FALLAS_BBDD.IDFALLAS_BBDD], 
            T.FECHA AS [FALLAS_BBDD.FECHA], 
            T.ERROR AS [FALLAS_BBDD.ERROR], 
            True AS _from0
        FROM ModelStoreContainer.FALLAS_BBDD AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// vista devuelta para ModelStoreContainer.MANTENIMIENTOS
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView38()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("ModelStoreContainer.MANTENIMIENTOS", @"
    SELECT VALUE -- Constructing MANTENIMIENTOS
        [Model.Store.MANTENIMIENTOS](T1.MANTENIMIENTOS_IDMANTENIMIENTO, T1.[MANTENIMIENTOS.AERONAVES_IDAERONAVE], T1.[MANTENIMIENTOS.ESTADO_IDESTADO], T1.MANTENIMIENTOS_OBS, T1.[MANTENIMIENTOS.COMPONENTES_IDCOMPONENTE])
    FROM (
        SELECT 
            T.IDMANTENIMIENTO AS MANTENIMIENTOS_IDMANTENIMIENTO, 
            T.AERONAVES_IDAERONAVE AS [MANTENIMIENTOS.AERONAVES_IDAERONAVE], 
            T.ESTADO_IDESTADO AS [MANTENIMIENTOS.ESTADO_IDESTADO], 
            T.OBS AS MANTENIMIENTOS_OBS, 
            T.COMPONENTES_IDCOMPONENTE AS [MANTENIMIENTOS.COMPONENTES_IDCOMPONENTE], 
            True AS _from0
        FROM EscHalconEntities.MANTENIMIENTOS AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// vista devuelta para EscHalconEntities.MANTENIMIENTOS
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView39()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("EscHalconEntities.MANTENIMIENTOS", @"
    SELECT VALUE -- Constructing MANTENIMIENTOS
        [Model.MANTENIMIENTOS](T1.MANTENIMIENTOS_IDMANTENIMIENTO, T1.[MANTENIMIENTOS.AERONAVES_IDAERONAVE], T1.[MANTENIMIENTOS.ESTADO_IDESTADO], T1.MANTENIMIENTOS_OBS, T1.[MANTENIMIENTOS.COMPONENTES_IDCOMPONENTE])
    FROM (
        SELECT 
            T.IDMANTENIMIENTO AS MANTENIMIENTOS_IDMANTENIMIENTO, 
            T.AERONAVES_IDAERONAVE AS [MANTENIMIENTOS.AERONAVES_IDAERONAVE], 
            T.ESTADO_IDESTADO AS [MANTENIMIENTOS.ESTADO_IDESTADO], 
            T.OBS AS MANTENIMIENTOS_OBS, 
            T.COMPONENTES_IDCOMPONENTE AS [MANTENIMIENTOS.COMPONENTES_IDCOMPONENTE], 
            True AS _from0
        FROM ModelStoreContainer.MANTENIMIENTOS AS T
    ) AS T1");
        }
    }
}
