//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class PILOTOS
    {
        public PILOTOS()
        {
            this.MEDICINAS = new HashSet<MEDICINAS>();
            this.VUELOS = new HashSet<VUELOS>();
        }
    
        public int IDUSUARIO { get; set; }
        public int HORAS_VOLADAS { get; set; }
        public string RUT { get; set; }
    
        public virtual USUARIOS USUARIOS { get; set; }
        public virtual ICollection<MEDICINAS> MEDICINAS { get; set; }
        public virtual ICollection<VUELOS> VUELOS { get; set; }
    }
}
