//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIOS
    {
        public USUARIOS()
        {
            this.CREDENCIALES = new HashSet<CREDENCIALES>();
        }
    
        public int IDUSUARIO { get; set; }
        public int ESTADO_IDESTADO { get; set; }
        public string RUT { get; set; }
        public string NOMBRES { get; set; }
        public string AP_PATERNO { get; set; }
        public string AP_MATERNO { get; set; }
        public string DOMICILIO { get; set; }
        public long TEL_CEL { get; set; }
        public Nullable<int> TEL_FIJO { get; set; }
        public string CORREO { get; set; }
    
        public virtual ADMINISTRADORES ADMINISTRADORES { get; set; }
        public virtual CONSULTORES CONSULTORES { get; set; }
        public virtual ICollection<CREDENCIALES> CREDENCIALES { get; set; }
        public virtual ESTADO ESTADO { get; set; }
        public virtual OPERARIOS OPERARIOS { get; set; }
        public virtual PILOTOS PILOTOS { get; set; }
    }
}
